server.port=8080

spring.datasource.url=${database_URL}
spring.datasource.username=${database_USER}
spring.datasource.password=${database_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
logging.level.org.springframework.mail=DEBUG
logging.level.javax.mail=DEBUG

spring.security.oauth2.client.registration.google.client-id=${Client_Id}
spring.security.oauth2.client.registration.google.client-secret=${Client_Secret}
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secret=${jwtsecret}
jwt.expiration=${jwtexpiry}